   %% Przygotowanie srodowiska
clear;
clc;

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\User\Desktop\Wspomaganie
%    Decyzji\Laboratorium\5\Dane.xlsx Worksheet: Arkusz1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/11/11 21:50:50

%% Import the data
[~, ~, raw] = xlsread('C:\Users\User\Desktop\Wspomaganie Decyzji\Laboratorium\4\Dane.xlsx','Arkusz1','A2:G31');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,2);
raw = raw(:,[1,3,4,5,6,7]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Lp = data(:,1);
Nazwa = cellVectors(:,1);
Cena = data(:,2);
RAM = data(:,3);
Dysk = data(:,4);
Przekatna = data(:,5);
Procesor = data(:,6);

%% Clear temporary variables
%clearvars data raw cellVectors;

%% Punkt rezerwacji
R = [10000 8 256 13 1.8]';

%% Punkt aspiracji
A = [6000 12 400 14 2.3;]';

%% Maksymalne wartosci kolumn danych
maxCena = max(Cena);    
maxRAM = max(RAM);    
maxDysk = max(Dysk);    
maxProcesor = max(Procesor);    
maxPrzekatna = max(Przekatna);

MAX = [ maxCena maxRAM maxDysk maxProcesor maxPrzekatna ]';

%% Przeskalowanie kolumn danych
%Cena = skaluj(Cena);
%RAM = skaluj(RAM);
%Dysk = skaluj(Dysk);
%Procesor = skaluj(Procesor);
%Przekatna = skaluj(Przekatna);

%% Przeskalowanie punktu rezerwacji
%for i=1:5
%    R(i) = R(i) / max( data(:, i+1) );
%end

%% Przeskalowanie punktu aspiracji
%for i=1:5
%    A(i) = A(i) / max( data(:, i+1) );
%end

%% Wykres nr 1 -> RAM = f(Cena)
figure(1);
hold on;

% Punkty oznaczajace laptopy
plot( Cena, RAM, 'gs',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5] );
grid on;
title('Iloœæ pamiêci RAM w zale¿noœci od ceny');
xlabel('Cena (z³)');
ylabel('RAM (GB)');

for k=1:length(Cena)
    sk = sprintf( '%d', k );
    text( Cena(k), RAM(k), sk, 'VerticalAlignment',...
    'Bottom', 'HorizontalAlignment', 'Center' );
end

% Umieszczenie na wykresie punktu rezerwacji
plot( R(1), R(2), 'gs',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5] );
text( R(1), R(2), 'R', 'VerticalAlignment', 'Bottom',...
    'HorizontalAlignment', 'Center' );

% Umieszczenie na wykresie punktu aspiracji
plot( A(1), A(2), 'gs',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5] );
text( A(1), A(2), 'A', 'VerticalAlignment', 'Bottom',...
    'HorizontalAlignment', 'Center' );

%x = 0:0.05:1;
%y = 0:0.05:1;
%[X,Y] = meshgrid(x, y);

%Z = oblicz(1,2,R,A);

%[C, h] = contour(X,Y,Z);

%set(h, 'LineColor', 'black');

hold off;
 
 

%% Wykres nr 2 -> Dysk = f(Cena)
figure(2);
hold on;

plot( Cena, Dysk, 'gs',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5] );
grid on;
title('Iloœæ pamiêci dyskowej w zale¿noœci od ceny');
xlabel('Cena (z³)');
ylabel('Dysk (GB)');




for k=1:length(Cena)
    sk = sprintf( '%d', k );
    text( Cena(k), Dysk(k), sk, 'VerticalAlignment',...
    'Bottom', 'HorizontalAlignment', 'Center' );
end

% Umieszczenie na wykresie punktu rezerwacji
plot( R(1), R(3), 'gs',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5] );
text( R(1), R(3), 'R', 'VerticalAlignment', 'Bottom',...
    'HorizontalAlignment', 'Center' );

% Umieszczenie na wykresie punktu aspiracji
plot( A(1), A(3), 'gs',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5] );
text( A(1), A(3), 'A', 'VerticalAlignment', 'Bottom',...
    'HorizontalAlignment', 'Center' );

%x = 0:0.05:1;
%y = 0:0.05:1;
%[X,Y] = meshgrid(x, y);

%Z = oblicz(1,3,R,A);

%[C, h] = contour(X,Y,Z);

%set(h, 'LineColor', 'black');

hold off;

%% Wykres nr 3 -> Procesor = f(Cena)
figure(3);
hold on;

plot( Cena, Procesor, 'gs',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5] );
grid on;
title('Szybkoœæ procesora w zale¿noœci od ceny');
xlabel('Cena (z³)');
ylabel('Procesor (GHz)');




for k=1:length(Cena)
    sk = sprintf( '%d', k );
    text( Cena(k), Procesor(k), sk, 'VerticalAlignment',...
    'Bottom', 'HorizontalAlignment', 'Center' );
end

% Umieszczenie na wykresie punktu rezerwacji
plot( R(1), R(5), 'gs',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5] );
text( R(1), R(5), 'R', 'VerticalAlignment', 'Bottom',...
    'HorizontalAlignment', 'Center' );

% Umieszczenie na wykresie punktu aspiracji
plot( A(1), A(5), 'gs',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5] );
text( A(1), A(5), 'A', 'VerticalAlignment', 'Bottom',...
    'HorizontalAlignment', 'Center' );

%x = 0:0.05:1;
%y = 0:0.05:1;
%[X,Y] = meshgrid(x, y);

%Z = oblicz(1,5,R,A);

%[C, h] = contour(X,Y,Z);

%set(h, 'LineColor', 'black');

hold off;


%% Wykres nr 4 -> RAM = f(Dysk)
figure(4);
hold on;

plot( Dysk, RAM, 'gs',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5] );
grid on;
title('Iloœæ pamiêci RAM w zale¿noœci od iloœci pamiêci dyskowej');
xlabel('Dysk (GB)');
ylabel('RAM (GB)');





for k=1:length(Cena)
    sk = sprintf( '%d', k );
    text( Dysk(k), RAM(k), sk, 'VerticalAlignment',...
    'Bottom', 'HorizontalAlignment', 'Center' );
end

% Umieszczenie na wykresie punktu rezerwacji
plot( R(3), R(2), 'gs',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5] );
text( R(3), R(2), 'R', 'VerticalAlignment', 'Bottom',...
    'HorizontalAlignment', 'Center' );

% Umieszczenie na wykresie punktu aspiracji
plot( A(3), A(2), 'gs',...
    'LineWidth',1,...
    'MarkerSize',6,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor',[0.5,0.5,0.5] );
text( A(3), A(2), 'A', 'VerticalAlignment', 'Bottom',...
    'HorizontalAlignment', 'Center' );

%x = 0:0.05:1;
%y = 0:0.05:1;
%[X,Y] = meshgrid(x, y);

%Z = oblicz(3,2,R,A);

%[C, h] = contour(X,Y,Z);

%set(h, 'LineColor', 'black');

hold off;
